### ISSUE TITLE
Pricing plans for drone specs as

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/iot-interns#1]
Write an article on the pricing plans for these specs.

https://paper.dropbox.com/doc/Pricing-plans-for-drone-specs-as--Af35ra8i26cgia06QwOiNdLIAQ-dWKBiQk1a02h3ImHWntCP

Focal min - FOV 94° (35 mm format equivalent) f/2.8 focus at ∞
ISO - 100 - 4800/3200
Image size - 4000×3000
Still Photography: 3/5/7 frames
Auto Exposure Bracketing (AEB)
Max capacity: 64 GB
Enables - JPEG/MP4
Operating Temperature - 32° to 104°F (0° to 50°C)
Size doesn't matter
Speed > 100mph
Vision - Forward + Downward
Velocity - >100 mph (15m above ground)
FOV - Forward: 60°(Horizontal), ±27°(Vertical), Downward: 70°(Front and Rear), 50°(Left and Right) - min
Altitude, Operating, Obstacle Sensory - min 50ft

**Comment by KevinChittilapilly** [comment]
I did a rough survey on the pricing of various drones that meet the required specs. I am posting my findings here.
[Drones.pdf](https://github.com/alice-sieve/iot-interns/files/3353280/Drones.pdf)

**Comment by tapaswenipathak** [comment]
Revised doc?

**Comment by tapaswenipathak** [comment]
https://paper.dropbox.com/doc/device-information--Ag6s91XAVwIUIHmzpiurvFxNAQ-QbKfzkC5cr88MEZEWBilf
