### ISSUE TITLE
Pulse and nerve scanning using Raspberry PI and Arduino

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/iot-interns#3]
- Pricing plans
- Specifications
- The device should be like a cell phone can be extended as walkable robot
- any open source project available
- how much memory we would need?
- The price should be as cheap as we can enable

Write an article on your findings.
https://paper.dropbox.com/doc/Pulse-and-nerve-scanning-using-Raspberry-PI-and-Arduino--Af26O33Q3GDdf_8awjF7BnZPAQ-5HMtttX9VpiTgCo7bFkCU

**Comment by KevinChittilapilly** [comment]
I made a HeartRate Monitor as a project for my college. The sensors were not that expensive. (Arduino I already had). I can further optimize it for nerve scanning as well

**Comment by KevinChittilapilly** [comment]
https://drive.google.com/open?id=1nfzLs4atgbvO2NJGZ9lUTuhgPPxFRR8T
This is a video demonstration of the same. Its just a prototype for now and cannot be commercialized.

**Comment by tapaswenipathak** [comment]
On Thu, Jun 27, 2019 at 5:19 PM Kevin Chittilapilly
<notifications@github.com> wrote:
>
> I made a HeartRate Monitor as a project for my college. The sensors were cheap. (Arduino I already had). I can further optimize it for nerve scanning as well

I don't only want numbers as output, I want a scan, we will chat in
Slack and write in the doc.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by tapaswenipathak** [comment]
On Thu, Jun 27, 2019 at 5:23 PM Kevin Chittilapilly
<notifications@github.com> wrote:
>
> https://drive.google.com/open?id=1nfzLs4atgbvO2NJGZ9lUTuhgPPxFRR8T
> This is a video demonstration of the same.

oh ok.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by tapaswenipathak** [comment]
@KevinChittilapilly you lead the paper doc. I am more of theoretical on this topic, I will ping you in the channel.

**Comment by KevinChittilapilly** [comment]
Sure
